apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kubearmorOperator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    kubearmor-app: {{ .Values.kubearmorOperator.name }}
spec:
  selector:
    matchLabels:
      kubearmor-app: {{ .Values.kubearmorOperator.name }}
  template:
    metadata:
      labels:
        kubearmor-app: {{ .Values.kubearmorOperator.name }}
    spec:
      containers:
      - name: {{ .Values.kubearmorOperator.name }}
        env:
        - name: KUBEARMOR_OPERATOR_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.global.azure.images.kubearmorOperator.registry }}/{{ .Values.global.azure.images.kubearmorOperator.image }}@{{ .Values.global.azure.images.kubearmorOperator.digest }}"
        imagePullPolicy: {{ .Values.kubearmorOperator.imagePullPolicy }}
      serviceAccountName: {{ .Values.kubearmorOperator.name }}
